name: Report a Problem
description: Let us know if something is not working as expected on the site.
labels:
  - bug
body:
  - type: textarea
    id: location
    attributes:
      label: Where is the problem?
      description: Briefly state the location.
      placeholder: |
        [Account Type] - [User Type] - [Affected Page] - [Specific Feature]
        Example: School - Student - Books - Books Preview
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Briefly describe the problem you experienced.
      placeholder: "Example: I clicked one of the preview books, but nothing happened."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      description: Briefly describe what should have happened.
      placeholder: "Example: After clicking, it should link me to another tab."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (Optional)
      placeholder: "Add any other context, screenshots, or videos."
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "High"
        - "Medium"
        - "Low"
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "No"
        - "Yes"